url: https://github.com/epinio/helm-charts/releases/download/epinio-1.5.1/epinio-1.5.1.tgz
version: 101.0.2
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
