url: https://github.com/kubernetes-sigs/node-feature-discovery/releases/download/v0.11.2/node-feature-discovery-chart-0.11.2.tgz
packageVersion: 01
# node-feature-discovery is only used as a dependency of sriov
doNotRelease: true
