url: https://neuvector.github.io/neuvector-helm/core-2.4.0.tgz
version: 101.0.2
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
