url: https://kubernetes-charts.banzaicloud.com/charts/logging-operator-3.17.10.tgz
version: 101.1.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
